name: Maestro UI Tests

on:
  push:
    branches: [ main ]

jobs:
  maestro-tests:
    runs-on: macos-latest  # or ubuntu-latest if you're testing Android only

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Run Maestro Tests
        run: maestro test .maestro/flows/maestro-project

